"""Add core models: users, destinations, aliases, sessions, magic_link_tokens

Revision ID: 1f21d4c2b037
Revises: 3b1990b09574
Create Date: 2025-12-24 22:04:26.488078

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1f21d4c2b037"
down_revision: Union[str, Sequence[str], None] = "3b1990b09574"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "magic_link_tokens",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_magic_link_tokens_email"), "magic_link_tokens", ["email"], unique=False
    )
    op.create_index(
        op.f("ix_magic_link_tokens_expires_at"),
        "magic_link_tokens",
        ["expires_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_magic_link_tokens_id"), "magic_link_tokens", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_magic_link_tokens_token_hash"),
        "magic_link_tokens",
        ["token_hash"],
        unique=True,
    )
    op.create_index(
        "ix_magic_tokens_email_expires",
        "magic_link_tokens",
        ["email", "expires_at"],
        unique=False,
    )
    op.create_index(
        "ix_magic_tokens_token_hash", "magic_link_tokens", ["token_hash"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index("ix_users_email_lower", "users", ["email"], unique=False)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "destinations",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("verified_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("verification_token", sa.String(length=255), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_destinations_email"), "destinations", ["email"], unique=False
    )
    op.create_index(op.f("ix_destinations_id"), "destinations", ["id"], unique=False)
    op.create_index(
        "ix_destinations_user_email", "destinations", ["user_id", "email"], unique=True
    )
    op.create_index(
        op.f("ix_destinations_user_id"), "destinations", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_destinations_verification_token"),
        "destinations",
        ["verification_token"],
        unique=False,
    )
    op.create_table(
        "sessions",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=255), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("user_agent", sa.String(length=512), nullable=True),
        sa.Column("ip_address", sa.String(length=45), nullable=True),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sessions_expires_at"), "sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_id"), "sessions", ["id"], unique=False)
    op.create_index("ix_sessions_token_hash", "sessions", ["token_hash"], unique=False)
    op.create_index(
        "ix_sessions_user_expires", "sessions", ["user_id", "expires_at"], unique=False
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "aliases",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("destination_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("domain", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["destination_id"], ["destinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_aliases_destination_id"), "aliases", ["destination_id"], unique=False
    )
    op.create_index(op.f("ix_aliases_id"), "aliases", ["id"], unique=False)
    op.create_index(
        op.f("ix_aliases_is_active"), "aliases", ["is_active"], unique=False
    )
    op.create_index(
        "ix_aliases_name_domain", "aliases", ["name", "domain"], unique=True
    )
    op.create_index(
        "ix_aliases_user_active", "aliases", ["user_id", "is_active"], unique=False
    )
    op.create_index(op.f("ix_aliases_user_id"), "aliases", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_aliases_user_id"), table_name="aliases")
    op.drop_index("ix_aliases_user_active", table_name="aliases")
    op.drop_index("ix_aliases_name_domain", table_name="aliases")
    op.drop_index(op.f("ix_aliases_is_active"), table_name="aliases")
    op.drop_index(op.f("ix_aliases_id"), table_name="aliases")
    op.drop_index(op.f("ix_aliases_destination_id"), table_name="aliases")
    op.drop_table("aliases")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_index("ix_sessions_user_expires", table_name="sessions")
    op.drop_index("ix_sessions_token_hash", table_name="sessions")
    op.drop_index(op.f("ix_sessions_id"), table_name="sessions")
    op.drop_index(op.f("ix_sessions_expires_at"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_destinations_verification_token"), table_name="destinations")
    op.drop_index(op.f("ix_destinations_user_id"), table_name="destinations")
    op.drop_index("ix_destinations_user_email", table_name="destinations")
    op.drop_index(op.f("ix_destinations_id"), table_name="destinations")
    op.drop_index(op.f("ix_destinations_email"), table_name="destinations")
    op.drop_table("destinations")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index("ix_users_email_lower", table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index("ix_magic_tokens_token_hash", table_name="magic_link_tokens")
    op.drop_index("ix_magic_tokens_email_expires", table_name="magic_link_tokens")
    op.drop_index(
        op.f("ix_magic_link_tokens_token_hash"), table_name="magic_link_tokens"
    )
    op.drop_index(op.f("ix_magic_link_tokens_id"), table_name="magic_link_tokens")
    op.drop_index(
        op.f("ix_magic_link_tokens_expires_at"), table_name="magic_link_tokens"
    )
    op.drop_index(op.f("ix_magic_link_tokens_email"), table_name="magic_link_tokens")
    op.drop_table("magic_link_tokens")
    # ### end Alembic commands ###
