"""Update alias model with labels, notes, and expiration

Revision ID: 847c897c6a58
Revises: 1765f27dd620
Create Date: 2025-12-30 14:42:46.450320

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "847c897c6a58"
down_revision: Union[str, Sequence[str], None] = "1765f27dd620"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "aliases", sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True)
    )
    op.add_column("aliases", sa.Column("note", sa.Text(), nullable=True))
    op.add_column(
        "aliases", sa.Column("labels", sa.ARRAY(sa.String(length=50)), nullable=True)
    )
    op.alter_column(
        "aliases",
        "name",
        existing_type=sa.VARCHAR(length=64),
        type_=sa.String(length=32),
        existing_nullable=False,
    )
    op.create_index("ix_aliases_expires_at", "aliases", ["expires_at"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_aliases_expires_at", table_name="aliases")
    op.alter_column(
        "aliases",
        "name",
        existing_type=sa.String(length=32),
        type_=sa.VARCHAR(length=64),
        existing_nullable=False,
    )
    op.drop_column("aliases", "labels")
    op.drop_column("aliases", "note")
    op.drop_column("aliases", "expires_at")
    # ### end Alembic commands ###
