"""Fix duplicate index definitions

Revision ID: d7960a2fd8bf
Revises: 1f21d4c2b037
Create Date: 2025-12-24 22:11:14.685752

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "d7960a2fd8bf"
down_revision: Union[str, Sequence[str], None] = "1f21d4c2b037"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_magic_link_tokens_token_hash"), table_name="magic_link_tokens"
    )
    op.drop_index(op.f("ix_magic_tokens_token_hash"), table_name="magic_link_tokens")
    op.create_unique_constraint(None, "magic_link_tokens", ["token_hash"])
    op.drop_index(op.f("ix_sessions_token_hash"), table_name="sessions")
    op.create_unique_constraint(None, "sessions", ["token_hash"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "sessions", type_="unique")
    op.create_index(
        op.f("ix_sessions_token_hash"), "sessions", ["token_hash"], unique=False
    )
    op.drop_constraint(None, "magic_link_tokens", type_="unique")
    op.create_index(
        op.f("ix_magic_tokens_token_hash"),
        "magic_link_tokens",
        ["token_hash"],
        unique=False,
    )
    op.create_index(
        op.f("ix_magic_link_tokens_token_hash"),
        "magic_link_tokens",
        ["token_hash"],
        unique=True,
    )
    # ### end Alembic commands ###
